name: project_template
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  logger: ^1.3.0
  dio: ^5.0.3
  get_it: ^7.2.0
  fluro: ^2.0.5
  shared_preferences: ^2.0.20
  provider: ^6.0.5
  dynamic_themes: ^1.1.0
  intl: ^0.17.0
  responsive_framework: ^0.2.0
  json_annotation: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.5.4
  build_runner: ^2.1.0
  build_test: ^2.1.3

flutter:

  uses-material-design: true

  assets:
    - images/
    - icons/

  fonts:
    - family: Vazir
      fonts:
        - asset: fonts/Vazir/Vazir-Regular.ttf
    - family: Comfortaa
      fonts:
        - asset: fonts/Comfortaa/Comfortaa-Regular.ttf

flutter_intl:
  main_locale: en_US
  enabled: true
  arb_dir: lib/localization/l10n
  output_dir: lib/localization/generated